### ISSUE TITLE
[Polymetis] Cartesian tracking issues

### ISSUE THREAD

**Issue by exhaustin** [facebookresearch/fairo#1336]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [x] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

This issue is made to keep track of the remaining improvements that can be done to improve tracking after the series of changes in #1307, #1255, #1308, #1334

### Further analysis of adaptive joint controllers (discussed in #1255)

The connection between the new adaptive controllers and the improved tracking is not well studied. Further analysis, visualization, especially across optimized gains for each controller, is desired.

### Need of better IK solutions (discussed in #1308)

Current shortcomings of the Pinocchio IK:
- Not-as-optimized performance
- Does not respect joint limits
- Does not consider null space movement within the cost

Thus it is desirable to seek alternative IK solutions to improve upon these axes.

## Current Behavior

Description of current behavior or functionality.

## Expected Behavior

Description of the expected behavior or functionality. In case of feature request, please add input and expected output.

## Steps to reproduce

Please add steps to reproduce the bug here along with the stack trace.

## Links to any relevant pastes or documents 

Please post links to any relevant documents that might contain any extra information.

## Checklist

Use this checklist if you are using this issue as a tracker:

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3 ...
