### ISSUE TITLE
Create RoBoPen Tracking Example

### ISSUE THREAD

**Issue by eugeniafeng** [facebookresearch/fairo#1349]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [x] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

Create Python scripts to run joint/EE trajectory tracking analysis using the RoBoPen dashboard. One for a single joint, performing sinusoidal movement and a chirp function, and another for the end effector following a square.

## Expected Behavior

Joint moves in a sinusoidal motion, and the dashboard displays the difference between the desired and actual position.
End effector moves in a square, and the dashboard displays the difference between the desired and actual position.
