### ISSUE TITLE
Memory bugfixes and updates for dashboard diffing

### ISSUE THREAD

**Issue by aszlam** [facebookresearch/fairo#25]
## Type of Issue

Select the type of issue:
- [x] Bug report (to report a bug)
- [x] Feature request (to request an additional feature)
- [x] Tracker (I am just using this as a tracker)
- [ ] Documentation Ask

## Description

Combination bugfixes and code cleanup of agent memory.   In part to support sending diffs of agent memory database to dashboard, and in part just to clean up old junk, and fix some outstanding junk. 

## Subissues:

- [ ] Several memory tables are not derived from main memory table; in particular Triples
- [ ]  lots of raw _db_writes in code.  make a wrapper that logs deletes, forces update of updated_time, etc.
- [ ]  clean up deletes more generally
