### ISSUE TITLE
droidlet slam improvements checklist 

### ISSUE THREAD

**Issue by anuragprat1k** [facebookresearch/fairo#730]
## Type of Issue

Adding a laundry list of improvements for slam on droidlet

- [ ] We need SLAM in memory for better correctness of things. For example, checking if an object in memory is in line of sight of the agent is not possible without knowing the obstacles (which is missing from memory)
- [ ] Modularize SLAM more to build the right abstractions - for example how the distance matrix in fmm planner is accessed should be opaque to slam. This has been a source of a bunch of indexing bugs (because (x,y) co-ordinates need to be accessed as (y,x))
- [ ] Add tests for fmm planner, slam.py
- [ ] How can we speed up the time of getting a slam exploration outcome (currently requires launching habitat + letting the agent run for minutes + visualizing the frames dumped)
- [ ] Handle exceptions in Slam gracefully - currently it crashes the agent.
- [ ] What are some better terminating conditions - currently it bails out when robot reaches a loc which is marked as an obstacle
- [ ] Make mover level APIs collision aware
- [ ] Improve slam visualization - integrate world_view branch for 3D visualization into the dashboard
- [ ] Move from print statements to logging 

Select the type of issue:
- [ ] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask
